# exemple de configuration

app:
  liste-projets:
    liste1:
      nom: liste projet1
      repertoires: /home/user/projets
      exclusions:
      defaut: true
    liste2:
      nom: autres projets
      repertoires: /home/user/autres-projets
      exclusions:
      defaut: false
  maj:
    message-commit: 'chore(version): préparation de la version VERSION'
  run:
    dir:
      nom: liste des fichiers
      commande: "dir :REPERTOIRE_PROJET:"
      shell: true
    echo:
      nom: affichage
      commande: ["echo", "bonjour à tous"]
      shell: true


