

app:
  liste-projets:
    projet-courant:
      nom: Projet courant
      repertoires: D:/projet/projectcontrol
      exclusions:
      defaut: true
    projets-principaux:
      nom: Tous les projets
      repertoires: D:/projet
      exclusions:
      defaut: false


